# Based on keysight's acquire_iq_700MHz_ATT_DL.yml
single_frequency_time_domain_iq:
  name: acquire_iq_700MHz_ATT_DL
  frequency: 739e6
  reference_level: 0
  sample_rate: 28e6
  duration_ms: 714
  nskip: 0