FROM tekrsa_usb

RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive \
                   apt-get install -qy --no-install-recommends \
                   git python3-setuptools python3-pip python3-numpy \
                   gcc python3-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED 1
RUN mkdir -p /src
WORKDIR /src
COPY ./ /src

ARG DOCKER_GIT_CREDENTIALS
RUN python3 -m pip install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements-dev.txt

ENTRYPOINT ["pytest"]