y_factor_cal:
  name: 3550-3650_Cal
  # Preselector configuration
  cal_source_idx: 0
  temp_sensor_idx: 1
  # Signal Analyzer Settings
  preamp_enable: True
  reference_level: -25
  attenuation: 0
  sample_rate: 14e6
  duration_ms: 1000
  nskip: 0
  frequency:
    - 3555e6
    - 3565e6
    - 3575e6
    - 3585e6
    - 3595e6
    - 3605e6
    - 3615e6
    - 3625e6
    - 3635e6
    - 3645e6
