single_frequency_time_domain_iq:
  name: 3555_IQ
  frequency: 3555e6
  reference_level: -25
  attenuation: 0
  preamp_enable: True
  sample_rate: 14e6
  duration_ms: 4000
  nskip: 0
  classification: UNCLASSIFIED
