y_factor_cal:
  name: 3555_Cal
  # Preselector configuration
  cal_source_idx: 0
  temp_sensor_idx: 1
  # Signal Analyzer Settings
  preamp_enable: True
  reference_level: -25
  attenuation: 0
  sample_rate: 14e6
  duration_ms: 1000
  nskip: 0
  frequency: 3555e6
