y_factor_cal:
  name: 3565_Cal_IIR
  # Preselector configuration
  cal_source_idx: 0
  temp_sensor_idx: 1
  noise_diode_on: noise_diode_on
  noise_diode_off: noise_diode_off
  # Signal Analyzer Settings
  preamp_enable: True
  reference_level: -25
  attenuation: 0
  sample_rate: 14e6
  duration_ms: 1000
  nskip: 0
  frequency: 3565e6
  # IIR Filter Settings:
  # Optionally apply a low-pass IIR filter before Y-Factor
  iir_apply: True
  iir_gpass_dB: 0.1
  iir_gstop_dB: 40
  iir_pb_edge_Hz: 5e6
  iir_sb_edge_Hz: 5.008e6
  iir_num_response_frequencies: 1000
