single_frequency_fft:
  name: 3625_M4
  rf_path: antenna
  frequency: 3625e6
  reference_level: -25
  attenuation: 0
  preamp_enable: True
  sample_rate: 14e6
  fft_size: 1400
  nffts: 4000
  nskip: 0
