single_frequency_time_domain_iq:
  name: 3655_IQ
  rf_path: antenna
  frequency: 3655e6
  reference_level: -25
  attenuation: 0
  preamp_enable: True
  sample_rate: 14e6
  duration_ms: 4000
  nskip: 0
