y_factor_cal:
  name: 3665_Cal_IIR
  # Preselector configuration
  cal_source_idx: 0
  temp_sensor_idx: 1
  # Signal Analyzer Settings
  preamp_enable: True
  reference_level: -25
  attenuation: 0
  sample_rate: 14e6
  duration_ms: 1000
  nskip: 0
  frequency: 3665e6
  # IIR Filter Settings:
  # Optionally apply a low-pass IIR filter before Y-Factor
  iir_apply: True
  iir_rp_dB: 0.1
  iir_rs_dB: 40
  iir_cutoff_Hz: 5e6
  iir_width_Hz: 8e3
