stepped_frequency_time_domain_iq:
  # 500 ms captures every 10 MHz
  name: CBRS_IQ_0dB_Attenuation
  rf_path: antenna
  reference_level: -25
  attenuation: 0
  preamp_enable: True
  sample_rate: 14e6
  duration_ms: 500
  nskip: 0
  frequency:
    - 3555e6
    - 3565e6
    - 3575e6
    - 3585e6
    - 3595e6
    - 3605e6
    - 3615e6
    - 3625e6
    - 3635e6
    - 3645e6
    - 3655e6
    - 3665e6
    - 3675e6
    - 3685e6
    - 3695e6
  classification: UNCLASSIFIED
