single_frequency_time_domain_iq:
  name: Example_Single_IQ
  frequency: 3555e6
  reference_level: -25
  attenuation: 0
  preamp_enable: True
  sample_rate: 14e6
  duration_ms: 100
  nskip: 0
  classification: UNCLASSIFIED
  calibration_adjust: True
  rf_path: antenna
