nasctn_sea_data_product:
  name: SEA_Measure_CBRS_EXT_MultiAttenuation
  rf_path: antenna
# IIR filter settings
  iir_gpass_dB: 0.1  # Max passband ripple below unity gain
  iir_gstop_dB: 40  # Minimum stopband attenuation
  iir_pb_edge_Hz: 5e6  # Passband edge frequency
  iir_sb_edge_Hz: 5.008e6  # Stopband edge frequency
# Mean/Max FFT settings
  nffts: 64e3
# PFP frame
  pfp_frame_period_ms: 10
# APD downsampling settings
  apd_bin_size_dB: 1.0  # Set to 0 or negative for no downsampling
  apd_max_bin_dBm: -30
  apd_min_bin_dBm: -180
# Time domain power statistics settings
  td_bin_size_ms: 10
# Sigan Settings
  preamp_enable: True
  reference_level:
    - -25  # 3540-3550 MHz
    - -21  # 3550-3560 MHz
    - -21  # 3560-3570 MHz
    - -21  # 3570-3580 MHz
    - -21  # 3580-3590 MHz
    - -21  # 3590-3600 MHz
    - -21  # 3600-3610 MHz
    - -21  # 3610-3620 MHz
    - -21  # 3620-3630 MHz
    - -21  # 3630-3640 MHz
    - -21  # 3640-3650 MHz
    - -5   # 3650-3660 MHz
    - -5   # 3660-3670 MHz
    - -5   # 3670-3680 MHz
    - -5   # 3680-3690 MHz
    - -5   # 3690-3700 MHz
    - -3   # 3700-3710 MHz
  attenuation:
    - 0   # 3540-3550 MHz
    - 4   # 3550-3560 MHz
    - 4   # 3560-3570 MHz
    - 4   # 3570-3580 MHz
    - 4   # 3580-3590 MHz
    - 4   # 3590-3600 MHz
    - 4   # 3600-3610 MHz
    - 4   # 3610-3620 MHz
    - 4   # 3620-3630 MHz
    - 4   # 3630-3640 MHz
    - 4   # 3640-3650 MHz
    - 20  # 3650-3660 MHz
    - 20  # 3660-3670 MHz
    - 20  # 3670-3680 MHz
    - 20  # 3680-3690 MHz
    - 20  # 3690-3700 MHz
    - 22  # 3700-3710 MHz
  sample_rate: 14e6
# Acquisition settings (3540-3710 MHz in 10 MHz steps, each 4s long)
  duration_ms: 4000
  nskip: 0
  frequency:
    - 3545e6
    - 3555e6
    - 3565e6
    - 3575e6
    - 3585e6
    - 3595e6
    - 3605e6
    - 3615e6
    - 3625e6
    - 3635e6
    - 3645e6
    - 3655e6
    - 3665e6
    - 3675e6
    - 3685e6
    - 3695e6
    - 3705e6
