y_factor_cal:
  name: calibrate_3555
  # Preselector configuration
  cal_source_idx: 0
  temp_sensor_idx: 1
  # Signal Analyzer Settings
  preamp_enable: True
  reference_level: -25
  attenuation: 0
  sample_rate: 14e6
  fft_size: 1400  # FFT setting to be deprecated
  nffts: 10000  # FFT setting to be deprecated
  nskip: 0
  frequency: 3555e6
