y_factor_cal:
  name: calibrate_3550-3700_iir
  # Signal Analyzer Settings
  preamp_enable: True
  reference_level: -25
  attenuation: 0
  sample_rate: 14e6
  fft_size: 1400  # FFT setting to be deprecated
  nffts: 10000  # FFT setting to be deprecated
  nskip: 0
  frequency:
    - 3555e6
    - 3565e6
    - 3575e6
    - 3585e6
    - 3595e6
    - 3605e6
    - 3615e6
    - 3625e6
    - 3635e6
    - 3645e6
    - 3655e6
    - 3665e6
    - 3675e6
    - 3685e6
    - 3695e6
  # IIR Filter Settings:
  # Optionally apply a low-pass IIR filter before Y-Factor
  iir_apply: True
  iir_rp_dB: 0.1
  iir_rs_dB: 40
  iir_cutoff_Hz: 5e6
  iir_width_Hz: 8e3
