single_frequency_fft:
  name: acquire_m4s_700MHz_T-Mobile_DL
  frequency: 731.5e6
  reference_level: -10
  sample_rate: 56e6
  fft_size: 2048
  nffts: 300
  nskip: 0
  classification: UNCLASSIFIED
  calibration_adjust: True
