name: Bandit

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run-bandit:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Checkout scos-tekrsa
        uses: actions/checkout@v3

      - name: Build scos-tekrsa
        run: pip install .[ci]

      - name: Run Bandit
        run: bandit -r src --format sarif --output out.sarif

      - name: Upload SARIF file to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: out.sarif
          category: bandit-gh
