name: Bandit

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run-bandit:
    name: Py${{ matrix.py }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        py:
          - "3.8"
          # - "3.9"
          # - "3.10"
    steps:
      - name: Set up Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Checkout scos-tekrsa
        uses: actions/checkout@v3

      - name: Build scos-tekrsa
        run: pip install .[tests]

      - name: Run Bandit
        run: bandit -r . -c pyproject.toml --format sarif --output out.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: out.sarif
          category: bandit-gh
