name: "Run scos-tekrsa Unit Tests"

on: push

jobs:
  test:
    name: Test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      maxtrix:
        os: Ubuntu
        py:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: Setup Python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v3
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Setup test suite
        run: tox r -vv --notest
      - name: Run test suite
        run: tox r --skip-pkg-install
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
